/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'linkedIn' : IDL.Text,
  'username' : IDL.Text,
  'instagram' : IDL.Text,
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'photoUrl' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'company' : IDL.Text,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const AnalyticsEntry = IDL.Record({
  'country' : IDL.Text,
  'source' : IDL.Variant({
    'qr' : IDL.Null,
    'nfc' : IDL.Null,
    'direct' : IDL.Null,
  }),
  'timestamp' : Time,
  'deviceType' : IDL.Variant({
    'desktop' : IDL.Null,
    'mobile' : IDL.Null,
    'unknown' : IDL.Null,
  }),
});
export const Lead = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'capturedAt' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
  'createProfile' : IDL.Func([UserProfile], [], []),
  'getAnalytics' : IDL.Func([IDL.Text], [IDL.Vec(AnalyticsEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeads' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
  'getPublicProfile' : IDL.Func([IDL.Text], [UserProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logProfileView' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'desktop' : IDL.Null,
          'mobile' : IDL.Null,
          'unknown' : IDL.Null,
        }),
        IDL.Text,
        IDL.Variant({ 'qr' : IDL.Null, 'nfc' : IDL.Null, 'direct' : IDL.Null }),
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'linkedIn' : IDL.Text,
    'username' : IDL.Text,
    'instagram' : IDL.Text,
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'photoUrl' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'company' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const AnalyticsEntry = IDL.Record({
    'country' : IDL.Text,
    'source' : IDL.Variant({
      'qr' : IDL.Null,
      'nfc' : IDL.Null,
      'direct' : IDL.Null,
    }),
    'timestamp' : Time,
    'deviceType' : IDL.Variant({
      'desktop' : IDL.Null,
      'mobile' : IDL.Null,
      'unknown' : IDL.Null,
    }),
  });
  const Lead = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'capturedAt' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
    'createProfile' : IDL.Func([UserProfile], [], []),
    'getAnalytics' : IDL.Func([IDL.Text], [IDL.Vec(AnalyticsEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeads' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
    'getPublicProfile' : IDL.Func([IDL.Text], [UserProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logProfileView' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'desktop' : IDL.Null,
            'mobile' : IDL.Null,
            'unknown' : IDL.Null,
          }),
          IDL.Text,
          IDL.Variant({
            'qr' : IDL.Null,
            'nfc' : IDL.Null,
            'direct' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };