/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsEntry {
  'country' : string,
  'source' : { 'qr' : null } |
    { 'nfc' : null } |
    { 'direct' : null },
  'timestamp' : Time,
  'deviceType' : { 'desktop' : null } |
    { 'mobile' : null } |
    { 'unknown' : null },
}
export interface Lead {
  'name' : string,
  'email' : string,
  'phone' : string,
  'capturedAt' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'linkedIn' : string,
  'username' : string,
  'instagram' : string,
  'name' : string,
  'whatsapp' : string,
  'photoUrl' : string,
  'email' : string,
  'website' : string,
  'company' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<[UserProfile], undefined>,
  'createProfile' : ActorMethod<[UserProfile], undefined>,
  'getAnalytics' : ActorMethod<[string], Array<AnalyticsEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeads' : ActorMethod<[string], Array<Lead>>,
  'getPublicProfile' : ActorMethod<[string], UserProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logProfileView' : ActorMethod<
    [
      string,
      { 'desktop' : null } |
        { 'mobile' : null } |
        { 'unknown' : null },
      string,
      { 'qr' : null } |
        { 'nfc' : null } |
        { 'direct' : null },
    ],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitLead' : ActorMethod<[string, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];